### ISSUE TITLE
Every time I start, I get these errors.

### ISSUE THREAD

**Issue by Tamago4a** [Exiled-Team/EXILED#435]
2.7.0-rc.1 and other virsions
I removed all plugins.
![Снимок1](https://user-images.githubusercontent.com/47304666/110094229-a6219e00-7dac-11eb-81f2-48257c3b2e68.PNG)
![Снимок](https://user-images.githubusercontent.com/47304666/110094236-a6ba3480-7dac-11eb-909f-c13ffe375732.PNG)

**Comment by galaxy119** [comment]
I'm not able to reproduce this. Are you sure Exiled.Events.dll is updated properly?
And the SCP:SL server?

**Comment by Tamago4a** [comment]
This is a SCPSL server on windows operating system. It has been updated. And I installed the latest version of exiled there. I can record the video it needs.

**Comment by galaxy119** [comment]
Nothing has been changed in relation to ghostmode in quite some time, but I believe that particular error is possible if the server has online_mode set to false.

But as to the first error, that can only happen if you are using Exiled.Events.dll version 2.4.4 or below on SCP:SL 10.2.2 or 2.5+ on SCP:SL 10.2.1

Because of this version mistmatch, I can't really help diagnose any other issues/errors/etc until you resolve that.
Make sure your SCP:SL server is correctly updated to SL version 10.2.2, and that all of your Exiled dll's are correctly updated to at least 2.5.0, though I recommend 2.7.0-rc.1.


You can verify the version of each individual DLL by running ``show plugins`` in the server console, and you can verify the SL version by what it says in the console during server startup.

**Comment by Tamago4a** [comment]
Sorry to waste your time. I forgot that some of my plugins require the "Exiled.Events.dll" file in the "dependencies" folder.
