### ISSUE TITLE
ev.Thrower in ExplodingGrenadeEventArgs is null.

### ISSUE THREAD

**Issue by Whanos** [Exiled-Team/EXILED#474]
Hey there,

ev.Thrower in ExplodingGrenadeEventArgs is always null - and I'm not sure if it's meant to be null.

Reproduction:

- Create a handler for ExplodingGrenadeEventArgs.
- Try and use ev.Thrower for something.

I'm not sure if I'm doing it wrong. Here's an example piece of code

```
public void OnExplodingGrenade(ExplodingGrenadeEventArgs ev)
{
    //stuff
    ev.Thrower.Hurt(10f, DamageTypes.Grenade, "test"); //this will return an "NullReferenceException" error
}
```

Thanks.

**Comment by Michal78900** [comment]
Cannot replicate the issue:
```cs
internal void OnExplodingGrenade(ExplodingGrenadeEventArgs ev)
{
      Log.Info(ev.Thrower != null);
      Log.Info(ev.Thrower);
      
      ev.Thrower.Hurt(10f, DamageTypes.Grenade, "test");
}
```
![image](https://user-images.githubusercontent.com/75911188/114548582-41394d80-9c60-11eb-8241-6128a908c6ae.png)

I'm also getting 10 damage from each grenade explode.

**Comment by Whanos** [comment]
@Michal78900 That's odd. Thanks for confirming - Could you check my code at [https://github.com/Whanos/WhanosSCPSLPlugins/blob/main/ThrowableMitosis/ThrowableMitosis/Handlers/MapHandler.cs](here) and check if it's just me then? It's the same as your code there, but I get an issue.

Additionally, what version of EXILED were you using?

**Comment by Michal78900** [comment]
2.9.4-beta Exiled

**Comment by iRebbok** [comment]
This doesn't seem to be an issue on our end, technically it can't be null because of
https://github.com/Exiled-Team/EXILED/blob/f239f2d906c62a4ce0387aaa00c4503de0b5ffeb/Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs#L61 & https://github.com/Exiled-Team/EXILED/blob/f239f2d906c62a4ce0387aaa00c4503de0b5ffeb/Exiled.Events/EventArgs/ExplodingGrenadeEventArgs.cs#L33

The game sets the `throwerGameObject` during the grenade data initialization, it could be the server player because the thrower left the server before the grenade exploded, but not null in any case. You also didn't provide the full code or the exception stacktrace, only a piece with access to the thrower variable, the exception can cause your code.

**Comment by Whanos** [comment]
I will check again soon. I was on 2.9.4-beta, and still had this error. I will report back soon when i fiddle about with the code some more.

Thanks for your help
